version: "3.9"

services:
  api:
    build: .
    container_name: devopsgpt_api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
      - vectordb

  postgres:
    image: postgres:15
    container_name: devopsgpt_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devopsgpt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: devopsgpt_redis
    ports:
      - "6379:6379"

  vectordb:
    image: qdrant/qdrant:latest
    container_name: devopsgpt_vectordb
    ports:
      - "6333:6333"
      - "6334:6334"

volumes:
  pgdata: 